services:
  app:
    image: webdevops/php-nginx:8.3-alpine
    container_name: app
    ports:
      - "8080:80" # 映射到宿主機的 8080 端口
    volumes:
      - ./laravel-prometheus-grafana:/app
      - ./nginx/status.conf:/opt/docker/etc/nginx/conf.d/status.conf
    environment:
      # Nginx 變數
      WEB_DOCUMENT_ROOT: /app/public  # 設置 Nginx 的文檔根目錄

      # PHP 變數
      PHP_DISPLAY_ERRORS: 1           # 顯示 PHP 錯誤
      PHP_MEMORY_LIMIT: 512M          # PHP 內存限制
      PHP_MAX_EXECUTION_TIME: 300     # 最大執行時間
      PHP_POST_MAX_SIZE: 100M         # 最大 POST 大小
      PHP_UPLOAD_MAX_FILESIZE: 100M   # 上傳文件大小限制
      PHP_DATE_TIMEZONE: "UTC"        # PHP 默認時區

      # 自定義變數
      APP_ENV: local                  # Laravel 等框架的環境設置
      DB_HOST: mysql                  # 資料庫主機
      DB_PORT: 3306                   # 資料庫端口
      DB_DATABASE: test               # 資料庫名稱
      DB_USERNAME: root               # 資料庫用戶名
      DB_PASSWORD: root               # 資料庫密碼

    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    depends_on:
      - app
    networks:
      - app-network

#  nginx:
#    fbuild: ./nginx/
#    container_name: nginx
#    volumes:
#      - ./laravel-prometheus-grafana:/var/www:cached
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 8080:8080

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.3
    container_name: nginx-prometheus-exporter
    command: -nginx.scrape-uri http://app:8080/stub_status
    ports:
      - 9113:9113
    depends_on:
      - app
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.55.0
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - '9090:9090'
    networks:
      - app-network

  renderer:
    image: grafana/grafana-image-renderer:3.11.6
    environment:
      BROWSER_TZ: Asia/Taipei
    ports:
      - '8081:8081'
    networks:
      - app-network

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: pass
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    depends_on:
      - prometheus
      - renderer
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge