global:
  scrape_interval: 5s # Server 抓取頻率
  external_labels:
    monitor: "my-monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "nginx_exporter"
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
        labels:
          service: nginx
  - job_name: "openresty"
    static_configs:
      - targets: ['nginx:9145']
        labels:
          service: openresty
#  - job_name: "app"
#    static_configs:
#      - targets: ['app']
#        labels:
#          service: app